In [1]:
import cv2 as cv
import numpy as np
import random

In [2]:
img = cv.imread('C:/Users/tripa/OpenCV/assets/Self.jpeg', -1)

In [3]:
img = cv.resize(img, (0,0), fx=0.5, fy=0.5) #resize

In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [5]:
print(img.shape) #blue green red [0, 0, 0] o - 255

(694, 553, 3)


In [6]:
print(img[0]) #Shows the first row

[[191 207 213]
 [191 207 213]
 [191 207 213]
 ...
 [186 194 193]
 [184 192 191]
 [191 199 198]]


In [7]:
print(img[257][45:400]) #pixels between 45 and 400

[[190 206 212]
 [190 206 212]
 [190 206 212]
 ...
 [ 13  10  19]
 [ 13  10  19]
 [ 13  10  19]]


How to change Pixle color

In [8]:
for i in range(200):#First 200 rows
    for j in range(img.shape[1]): #To modify the entire column in 200 rows
        img[i][j] = [random.randint(0,255), random.randint(0, 255), random.randint(0, 255)]

In [9]:
cv.imshow('Image', img)
cv.waitKey(0)
cv.destroyAllWindows()

Coppy one part of the image to another part

In [10]:
img = cv.imread('C:/Users/tripa/OpenCV/assets/Self.jpeg', -1)

In [11]:
Nose_Part = img[650:750, 550:650]
img[100:200, 550:650] = Nose_Part

In [12]:
cv.imshow('Image', img)
cv.waitKey(0)
cv.destroyAllWindows()